import json

import streamlit as st

from reviewer import review_code, ReviewError

st.set_page_config(
    page_title="Smart Code Reviewer",
    page_icon="🔍",
    layout="wide",
    initial_sidebar_state="collapsed",
)

st.markdown("""
<style>
.stProgress > div > div > div > div { border-radius: 4px; }

.badge-critical   { background:#fee2e2; color:#dc2626; padding:2px 8px; border-radius:12px; font-size:12px; font-weight:600; }
.badge-warning    { background:#fef3c7; color:#d97706; padding:2px 8px; border-radius:12px; font-size:12px; font-weight:600; }
.badge-suggestion { background:#dbeafe; color:#2563eb; padding:2px 8px; border-radius:12px; font-size:12px; font-weight:600; }

.positive-box {
    background: #f0fdf4;
    border-left: 4px solid #16a34a;
    padding: 14px 16px;
    border-radius: 6px;
    margin-top: 8px;
}
</style>
""", unsafe_allow_html=True)


# ── Helpers ───────────────────────────────────────────────────────────────────
def score_color(score: float) -> str:
    """Hex color for a 0-10 score: green / amber / red."""
    if score >= 8:
        return "#16a34a"
    if score >= 6:
        return "#d97706"
    return "#dc2626"


def grade_for(score: float):
    """Return a (label, color) badge for the overall score."""
    if score >= 8:
        return "Excellent", "#16a34a"
    if score >= 6:
        return "Good", "#16a34a"
    if score >= 4:
        return "Needs work", "#d97706"
    return "Critical issues", "#dc2626"


def build_markdown_report(r: dict, lines) -> str:
    """Render the review as a portable Markdown report for download."""
    icon = {"critical": "🔴", "warning": "🟡", "suggestion": "🔵"}
    out = [
        "# 🔍 Smart Code Review Report",
        "",
        f"**Language:** {r.get('language', 'Unknown')}  ",
        f"**Overall score:** {r.get('overall_score', 0):.1f} / 10  ",
        f"**Lines reviewed:** {lines}",
        "",
        f"> {r.get('summary', '')}",
        "",
        "## Dimension scores",
        "",
    ]
    for key, label in (("readability", "Readability"),
                       ("structure", "Structure"),
                       ("maintainability", "Maintainability")):
        d = r.get("dimensions", {}).get(key, {})
        out.append(f"- **{label}:** {d.get('score', 0):.1f}/10 — {d.get('summary', '')}")

    out += ["", "## Issues", ""]
    issues = r.get("issues", [])
    if not issues:
        out.append("_No issues found._")
    else:
        for issue in issues:
            sev = issue.get("severity", "suggestion")
            loc = f" (line {issue['line']})" if issue.get("line") else ""
            out.append(f"- {icon.get(sev, '🔵')} **{sev.capitalize()}**{loc} — {issue.get('description', '')}")
            out.append(f"  - _Fix:_ {issue.get('suggestion', '')}")

    out += ["", "## What's done well", "", r.get("positive", "") or "_—_", "",
            "---", "_Generated by Smart Code Reviewer · Powered by Claude_"]
    return "\n".join(out)


# ── Header ────────────────────────────────────────────────────────────────────
st.title("🔍 Smart Code Reviewer")
st.caption(
    "AI-powered review for **readability**, **structure**, and **maintainability** "
    "— catch issues before human review."
)
st.divider()

col_left, col_right = st.columns([2, 3], gap="large")

# ── Left column: Input ────────────────────────────────────────────────────────
with col_left:
    st.subheader("Code Input")

    tab_paste, tab_upload = st.tabs(["📋 Paste Code", "📁 Upload File"])

    with tab_paste:
        pasted = st.text_area(
            "code_paste",
            height=340,
            placeholder="# Paste your code here…\ndef greet(name):\n    print('Hello, ' + name)",
            label_visibility="collapsed",
        )

    with tab_upload:
        uploaded = st.file_uploader(
            "Upload a source file",
            type=["py", "js", "ts", "jsx", "tsx", "java", "cpp", "c",
                  "go", "rb", "php", "cs", "rs", "swift", "kt", "r", "sh"],
            label_visibility="collapsed",
        )
        file_code = ""
        if uploaded is not None:
            file_code = uploaded.getvalue().decode("utf-8", errors="replace")
            preview = file_code[:3000] + ("…" if len(file_code) > 3000 else "")
            st.code(preview, language="text")

    # An uploaded file takes precedence; otherwise use pasted text.
    if uploaded is not None and file_code.strip():
        code = file_code
    else:
        code = pasted

    if uploaded is not None and file_code.strip() and pasted.strip():
        st.caption("ℹ️ Both inputs present — reviewing the **uploaded file**. Remove it to use pasted code.")

    language = st.selectbox(
        "Language",
        ["Auto-detect", "Python", "JavaScript", "TypeScript", "Java",
         "C++", "C", "Go", "Ruby", "PHP", "C#", "Rust", "Swift", "Kotlin", "R", "Bash"],
        index=0,
        help="Leave on Auto-detect unless the model misidentifies the language.",
    )
    lang = "auto" if language == "Auto-detect" else language.lower()

    review_clicked = st.button(
        "🔍 Review Code",
        type="primary",
        use_container_width=True,
        disabled=not code.strip(),
    )

    if not code.strip():
        st.caption("Paste code or upload a file to enable the review.")

# ── Right column: Results ─────────────────────────────────────────────────────
with col_right:
    st.subheader("Review Results")

    if review_clicked and code.strip():
        with st.spinner("Analyzing your code…"):
            try:
                st.session_state["result"] = review_code(code, lang)
                st.session_state["code_len"] = len(code.splitlines())
            except ReviewError as e:
                st.session_state.pop("result", None)
                st.error(str(e))
            except Exception as e:  # noqa: BLE001 — last-resort guard for the UI
                st.session_state.pop("result", None)
                st.error(f"Unexpected error: {e}")

    if "result" not in st.session_state:
        st.info("Your review will appear here once you submit code.", icon="💡")
    else:
        r = st.session_state["result"]
        lines = st.session_state.get("code_len", "—")

        # ── Overall score ─────────────────────────────────────────────────────
        score = float(r.get("overall_score", 0))
        grade, gcolor = grade_for(score)

        mc1, mc2, mc3 = st.columns(3)
        mc1.metric("Overall Score", f"{score:.1f} / 10")
        mc2.metric("Language", r.get("language", "Unknown"))
        mc3.metric("Lines reviewed", lines)

        st.markdown(
            f"<span style='background:{gcolor}1a;color:{gcolor};padding:3px 12px;"
            f"border-radius:12px;font-weight:600;font-size:13px'>{grade}</span>",
            unsafe_allow_html=True,
        )

        if r.get("summary"):
            st.write(r["summary"])

        st.divider()

        # ── Dimension scores ──────────────────────────────────────────────────
        st.markdown("**Dimension Scores**")
        dims = r.get("dimensions", {})
        dc1, dc2, dc3 = st.columns(3)
        for col, key, label in [
            (dc1, "readability", "Readability"),
            (dc2, "structure", "Structure"),
            (dc3, "maintainability", "Maintainability"),
        ]:
            d = dims.get(key, {})
            s = float(d.get("score", 0))
            with col:
                st.markdown(f"**{label}**")
                st.progress(s / 10)
                st.markdown(
                    f"<span style='color:{score_color(s)};font-size:20px;font-weight:700'>{s:.1f}</span>/10",
                    unsafe_allow_html=True,
                )
                st.caption(d.get("summary", ""))

        st.divider()

        # ── Issues ────────────────────────────────────────────────────────────
        issues = r.get("issues", [])
        counts = {sev: sum(1 for i in issues if i.get("severity") == sev)
                  for sev in ("critical", "warning", "suggestion")}
        st.markdown(
            f"**Issues** &nbsp; "
            f"<span class='badge-critical'>🔴 {counts['critical']} critical</span>&nbsp;"
            f"<span class='badge-warning'>🟡 {counts['warning']} warning</span>&nbsp;"
            f"<span class='badge-suggestion'>🔵 {counts['suggestion']} suggestion</span>",
            unsafe_allow_html=True,
        )
        st.write("")

        if not issues:
            st.success("No issues found — great code!", icon="✅")
        else:
            sev_icon = {"critical": "🔴", "warning": "🟡", "suggestion": "🔵"}
            for issue in issues:  # already sorted critical → suggestion
                sev = issue.get("severity", "suggestion")
                line_ref = issue.get("line")
                line_str = f"Line {line_ref} — " if line_ref else ""
                label = f"{sev_icon.get(sev, '🔵')} {line_str}{issue.get('description', '')}"
                with st.expander(label[:100]):
                    st.markdown(f"**Issue:** {issue.get('description', '')}")
                    st.markdown(f"**Suggestion:** {issue.get('suggestion', '')}")
                    st.caption(f"Category: {issue.get('category', '—')}  |  Severity: {sev}")

        st.divider()

        # ── Positive highlight ────────────────────────────────────────────────
        if r.get("positive"):
            st.markdown(
                f"<div class='positive-box'>✅ <strong>What's done well</strong><br>{r['positive']}</div>",
                unsafe_allow_html=True,
            )

        # ── Export + clear ────────────────────────────────────────────────────
        st.write("")
        ec1, ec2, ec3 = st.columns([2, 2, 1])
        ec1.download_button(
            "⬇️ Markdown report",
            build_markdown_report(r, lines),
            file_name="code-review.md",
            mime="text/markdown",
            use_container_width=True,
        )
        ec2.download_button(
            "⬇️ JSON data",
            json.dumps(r, indent=2),
            file_name="code-review.json",
            mime="application/json",
            use_container_width=True,
        )
        if ec3.button("Clear", use_container_width=True):
            st.session_state.pop("result", None)
            st.session_state.pop("code_len", None)
            st.rerun()

